### PR TITLE
docs(app): add doc on clean and delete application

### PR DESCRIPTION
**Pull request by uguy**
Add documentation about:

- deleting application
- cleaning application's BPM data

Relates to https://bonitasoft.atlassian.net/browse/BON-396

### CODE REVIEW

**Comment by tbouffard** [comment]
@Yves-Jacq  here are two proposal
- from @uguy: 953c020
- from @tbouffard (and ChatGPT) minor modifications from the previous commit: f8ceeaf

**Comment by uguy** [comment]
imho ChatGPT version is better

**Review by Yves-Jacq — APPROVED** [review]
Ok for me

**Review by tbouffard — APPROVED** [review]
All stakeholders approved, so ready to merge

**Pull request merged**
